---
- name: Deploy WAR file from Ansible master to remote node
  hosts: 172.31.44.249
  become: true
  tasks:
    - name: Ensure destination directory exists and set permissions
      ansible.builtin.file:
        path: /opt/apache-tomcat-8.5.99/webapps
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy file
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/ProjectInsurance/target/Insurance-0.0.1-SNAPSHOT.jar
        dest: /opt/apache-tomcat-8.5.99/webapps/
