---
- name: Deploy WAR file to Tomcat server
  hosts: 172.31.44.249
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: /var/lib/jenkins/workspace/ProjectInsurance/target/Insurance-0.0.1-SNAPSHOT.war
        dest: /opt/apache-tomcat-8.5.99/webapps/
        remote_src: yes
      notify: Restart Tomcat
    
